LPSiteNotification=function(){var p,y=!1,z;z=function(a){var b=a.target,c=$('input:not([type]):visible,input[type="text"]:visible,input[type="email"]:visible,input[type="password"]:visible'),d;a:{d=0;for(var e=c.length;d<e;++d)if("password"===c[d].type&&c[d].value){d=!0;break a}d=!1}if(d){d=b;for(b=[];d&&d.parentElement&&d.parentElement!==p;)b.unshift(d.parentElement),d=d.parentElement;d=0;for(e=c.length;d<e;++d){var f=c[d];if(f.value)for(var f=f.parentElement,g=null;f;){"FORM"===f.nodeName&&(g=f);
var h=b.indexOf(f);if(-1<h){g?a.form=g:a.genericForm=b[h];m(a);return}f=f.parentElement}}}};var m,A,r=["submit","click","keydown"],q={},s=!1;A=function(a,b){r.hasOwnProperty(a)?(q[a]=b,s||(s=!0,setTimeout(function(){for(var a=0;a<r.length;++a){var b=r[a];if(q.hasOwnProperty(b)){q[b]();break}}s=!1;q={}},0))):b()};m=function(a){var b=a.form||a.genericForm;if(b){var c=$(b).find('input:not([type]):visible,input[type="text"]:visible,input[type="email"]:visible,input[type="password"]:visible');if(a.form){for(var b=
a.form,d=[],e={},f=0;f<b.length;++f){var g=b[f];if(g.value&&!e.hasOwnProperty(g.value)&&("hidden"===g.type||!$(g).is(":visible"))){e[g.value]=!0;var h=LPContentScriptTools.findTextParent({searches:g.value,exactMatch:!0});h&&(h.parent&&"OPTION"!==h.parent.nodeName&&$(h.parent).is(":visible"))&&d.push(g)}}c=d.concat(c.toArray())}for(var j=[],m=!1,b=0;b<c.length;++b)if(d=c[b],d.value){for(var e=d,f=e.type,g=e.value,h=e.id,q=e,l=["name","ng-model","data-reactid"],n={},k=0;k<l.length;++k){var p=q.getAttribute(l[k]);
p&&(n[l[k]]=p)}f={type:f,value:g,id:h,attributes:n};"password"!==f.type&&"disc"===$(e).css("text-security")&&(f.type="password");e=f;"password"===e.type?m=!0:e.value=t.getUnmaskedValue(d,a.form);e.formname=a.form?a.form.getAttribute("name"):"";j.push(e)}A(a.type,function(){var b={url:document.location.href,top:window===top,fields:j,generatedPassword:a.generatedPassword};m?(a.type&&(y=!0),bg.LPTabState.processPasswordSubmit({formData:b,callback:a.generatedPassword?null:u})):0<c.length&&bg.LPTabState.processTextSubmit(b)})}};
var u;u=function(a){LPContentScriptTools.isUnloading()||(Topics.get(Topics.SITE_NOTIFICATION_STATE).publish(a),bg.get("LPContentScriptFeatures").new_save_site&&a.dialogData&&csTop.LPSiteNotification.showSiteNotification(a))};var B=function(a){for(;a;){if("FORM"===a.nodeName)return a;a=a.parentElement}return null},v,C=function(a){a=a.toLowerCase();return-1<a.indexOf("submit")||-1<a.indexOf("save")},w=function(a){a=a.attributes;for(var b=0;b<a.length;++b){var c=a[b];if(C(c.name)||C(c.value))return!0}return!1};
v=function(a){if("INPUT"===a.nodeName)return"submit"===a.type?!0:"button"===a.type?w(a):!1;for(;0===a.getElementsByTagName("input").length;){if("BUTTON"===a.nodeName)return"submit"===a.type||w(a);if(w(a))return!0;a=a.parentElement}return!1};var t,l=!1,j=[];Topics.get(Topics.FILLED_GENERATED_PW).subscribe(function(a){x({target:a.element,generatedPassword:a.password})});Topics.get(Topics.CLEAR_DATA).subscribe(function(){D()});Topics.get(Topics.LOGIN).subscribe(function(){E()});var n=function(a){return function(b){if(!1!==
b.isTrusted)try{a(b)}catch(c){console.log(c)}}},x=function(a){a.form=B(a.target);a.form?m(a):z(a)},k={submit:n(function(a){m({form:B(a.target),submit:!0,type:a.type})}),click:n(function(a){v(a.target)&&x({target:a.target,type:a.type})}),keydown:n(function(a){var b=a.target;if(b!==p&&13===(a.keyCode||a.which))("INPUT"===b.nodeName||v(b))&&x({target:b,type:a.type})}),change:n(function(a){a=a.target;if("INPUT"===a.nodeName&&a.value)switch(a.type){case "text":case "email":for(var b=0;b<j.length;++b)if(j[b].input===
a){j[b].value=a.value;return}j.push({input:a,value:a.value})}})},E=function(){if(!l){for(var a in k)document.addEventListener(a,k[a],!0);l=!0}},D=function(){if(l){for(var a in k)document.removeEventListener(a,k[a],!0);l=!1}j=[]};t={setup:E,teardown:D,getUnmaskedValue:function(a,b){if(a.value){var c;for(c=0;c<j.length;++c){var d=j[c];if(d.input===a&&d.value!==a.value)return d.value}if(b)for(c=0;c<b.length;++c)if(d=b[c],b[c]!==a&&("hidden"===b[c].type||!$(b[c]).is(":visible"))&&b[c].value&&b[c].value.length===
a.value.length&&b[c].value[0]===a.value[0]&&b[c].value[b[c].value.length-1]===a.value[a.value.length-1])return d.value}return a.value}};Topics.get(Topics.INITIALIZED).subscribe(function(){p=document.body;bg.get("lploggedin")&&(t.setup(),window===top&&bg.LPTabState.getSiteNotification({callback:u}))});return{formExists:function(a,b){var c=0,d=setInterval(function(){++c;var e;a:{for(e=0;e<a.fields.length;++e){var f=a.fields[e];if("password"===f.type){var g;if(f.id)g=$(document.getElementById(f.id));
else for(var h in f.attributes)if(g=$("input["+h+'="'+f.attributes[h]+'"]'),0<g.length)break;e=g&&0<g.length&&g.is(":visible")?a.passwordChangeForm?g.val()===f.value:!0:!1;break a}}e=!1}if(!e||4<c||!y)clearInterval(d),b(e)},1E3)},showSiteNotification:function(a){a.postSetup=function(){Topics.get(Topics.SITE_NOTIFICATION).publish(b)};var b=LPFrame.openDialog("contentScriptSite",a,{css:{top:10,right:10}})}}}();
