var SiteDialog=function(m){DialogWithGroupInput.call(this,m,{confirmOnClose:!1,hideButtons:!0,hideHeader:!0,type:Account,additionalClasses:"lmiDialog"});this.tiles=[];this.selectedTile=this.activeTile=null;this.submitted=this.isSelectable=!1};SiteDialog.prototype=Object.create(DialogWithGroupInput.prototype);SiteDialog.prototype.constructor=SiteDialog;
(function(){SiteDialog.prototype.initialize=function(b){DialogWithGroupInput.prototype.initialize.apply(this,arguments);var a=this;b.on("click",".neverSave",function(){bg.handleNeverURL({action:"never",cmd:"neverdomain",url:a.data.defaultData.url,fromsave:!0});bg.IntroTutorial.setState({enabled:!1});a.sendTrackingEvent("never");a.close()});a.backButton=b.find("#close").bind("click",function(){a.data.generatedPassword?a.data.generatedPasswordSaved?(a.dialogContent.css({height:a.dialogContent.css("height")}),
a.$element.addClass("removeGeneratedConfirmation"),a.sendTrackingEvent("undo")):(a.sendTrackingEvent("discard"),a.close()):(a.sendTrackingEvent("notnow"),a.close())});a.nextButton=b.find("#submit").bind("click",function(){a.isSelectable?a.selectedTile&&a.submit():a.submit()});b.find("#closeConfirmation").bind("click",function(){a.close()});b.find("#deleteGenerated").bind("click",function(){a.vaultItem.deleteItem({confirm:!1});a.close()});b.find(".addNewSiteButton").bind("click",function(){a.tiles[0].showDetails({clearErrors:!0,
callback:function(){a.clearFields();a.defaultFields(a.data);a.originalData=a.getData();a.populateFields(a.data.dialogData);a.setAddText()}});a.tiles[0].unselect();a.tiles[0].setSelectable(!1);for(var b=a.tiles.slice(),e=1;e<b.length;++e)b[e].remove();$(this).hide()})};SiteDialog.prototype.sendTrackingEvent=function(b){var a=this.clickedEdit?"savesiteedit":"savesiteseen";b={action:b};this.clickedEdit&&$.extend(b,{changedEmail:this.inputFields.unencryptedUsername.getValue()!==this.postSetupData.unencryptedUsername,
changedPassword:this.inputFields.password.getValue()!==this.postSetupData.password,showedPassword:this.activeTile?this.activeTile.showedPassword():!1});bg.sendLpImprove(a,b)};SiteDialog.prototype.setAddText=function(){this.$element.find(".question").text(Strings.translateString("Add to LastPass?"));this.nextButton.text(Strings.translateString("Add"))};var m=function(b,a,c){var e=$.extend({},b.defaultData);a&&$.extend(e,a.getFormData($.extend(c,DialogInput.getProperties(b.dialogData),DialogInput.getProperties(b.defaultData))));
return e};SiteDialog.prototype.hasDuplicates=function(){for(var b=0;b<this.tiles.length;++b)if(0<this.tiles[b].getDuplicates().length)return!0;return!1};SiteDialog.prototype.setup=function(b,a){a.saveOptions={saveFromSubmit:a.dialogData.fields?!0:!1,source:"saveSite"};b.find(".addSiteFavicon").append(LPTools.createElement("img",{"class":"favicon",src:a.favicon?a.favicon:"images/site/world.png"}));for(var c=this,e=!1,F=b.find(".tileContainer"),g=b.find(".question"),f=b.find(".explanation"),q=b.find(".dialogForm"),
w=b.find(".tile.template"),G=b.find(".deleteOverlayContainer.template"),x,j={},h=w.find("[dialogFieldDisplay]"),k=0;k<h.length;++k)j[h[k].getAttribute("dialogFieldDisplay")]=!0;x=j;var y=DialogInput.getProperties(c.inputFields),j=function(a){a=a||{};var b=this,d=w.clone().removeClass("template"),g=d.find(".summaryView .tileTable"),j=d.find(".addSiteFavicon"),h=d.find(".tileEdit").detach(),f=d.find(".checkmark").detach(),l=null,n=c.data,p=!1,k=!1,u=null,z=!1,H=m(n,a.site,y),r=$.extend(m(n,a.site,y),
n.dialogData),s=null,B=function(a){a&&c.clearErrors();c.originalData=H;c.populateFields(r)};this.showedPassword=function(){return z};this.getDialogData=function(){return r};this.getDuplicates=function(){if(null===s&&(s=[],n.defaultData.unencryptedUsername)){var a=bg.hostof(r.url);c.tiles.forEach(function(c){var d=c.getDialogData();c!==b&&bg.hostof(d.url)===a&&s.push(c)})}return s};this.handleChange=function(a,b){c.requestAnimationFrame(function(c){var e=LPTools.getOption(b,"animate",!0);e?d.addClass("animated transition"):
d.removeClass("animated transition");var g=function(a){d.removeClass("transition");c({callback:a&&a.callback})};a(function(a){var b=LPTools.getOption(a,"tileHeight",d.children().first().outerHeight()),c=d.height();d.css("height",b);if(b!==c&&e){var A=function(b){b.target===this&&(a&&a.transitionEndHandler&&a.transitionEndHandler(),g(a),d.unbind("transitionend",A))};d.bind("transitionend",A)}else g(a)})})};this.showDetails=function(a){c.clickedEdit||(c.sendTrackingEvent("edit"),c.clickedEdit=!0);n.generatedPasswordSaved&&
c.nextButton.text(Strings.translateString("Update"));null===u&&(u=d.height());this.handleChange(function(g){c.activeTile&&c.activeTile!==b&&c.activeTile.hideDetails();c.activeTile=b;B(a&&a.clearErrors);d.find(".tileContent").append(q);requestAnimationFrame(function(){d.addClass("details");e||(e=!0,c.adjustView(!0));g()});a&&a.callback&&a.callback()},a)};this.preSubmit=function(){c.activeTile!==this&&(c.activeTile&&(c.activeTile.hideDetails(),c.activeTile=null),B());c.vaultItem=a.site};this.hideDetails=
function(){r=c.getData();var a=q.clone();this.handleChange(function(b){d.find(".tileContent").append(a);requestAnimationFrame(function(){d.removeClass("details");b({transitionEndHandler:function(){a.remove()},tileHeight:u})})})};this.unselect=function(){p&&(c.selectedTile=null,p=!1,d.removeClass("selected"),c.$element.removeClass("selected"),c.nextButton.prop("disabled",!0))};this.toggleSelect=function(){p?(this.unselect(),this.getDuplicates().forEach(function(a){a.hideDeleteOverlay()})):(this.getDuplicates().forEach(function(a){a.showDeleteOverlay()}),
c.tiles.forEach(function(a){a.unselect()}),c.selectedTile=this,p=!0,d.addClass("selected"),c.$element.addClass("selected"),c.nextButton.prop("disabled",!1))};this.remove=function(){d.remove();for(var a=0;a<c.tiles.length;++a)if(c.tiles[a]===this){c.tiles.splice(a,1);break}};this.showDeleteOverlay=function(){null===l&&(l=G.clone().removeClass("template"),l.find(".cancelDeleteButton").bind("click",this.hideDeleteOverlay),l.find(".deleteButton").bind("click",function(){a.site.deleteItem({confirm:!1,
success:function(){b.remove()}});b.hideDeleteOverlay()}));d.append(l);requestAnimationFrame(function(){d.addClass("duplicate")})};this.hideDeleteOverlay=function(){d.removeClass("duplicate");l.one("transitionend",function(){d.hasClass("duplicate")||l.detach()})};this.setSelectable=function(a){k=a;a=d.find(".favicon");k?(a.addClass("hoverFadeOut"),c.$element.addClass("selectable"),c.nextButton.prop("disabled",!0)):(a.removeClass("hoverFadeOut"),c.$element.removeClass("selectable"),c.nextButton.prop("disabled",
!1))};h.bind("click",function(){b.showDetails({clearErrors:!0})});f.bind("click",function(){b.toggleSelect()});d.on("click",".showPassword",function(){z=!0});var t=!1;d.bind("mouseenter",function(){t=!0;g.append(h);k&&j.append(f);requestAnimationFrame(function(){t&&d.addClass("hover")})});d.bind("mouseleave",function(){t=!1;d.removeClass("hover").one("transitionend",function(){t||(h.detach(),p||f.detach())})});F.append(d);for(var I=a.site?a.site.getFormData(x):n.defaultData,C=d.find("[dialogFieldDisplay]"),
v=0;v<C.length;++v){var D=C[v],E=I[D.getAttribute("dialogFieldDisplay")];E&&(D.textContent=E)}c.tiles.push(this)};if(a.matchingSites)if(0===a.matchingSites.length)a.generatedPasswordSaved?(g.text(Strings.translateString("Nice! We've now added this to LastPass")),this.nextButton.text(Strings.translateString("Got it")),this.backButton.text(Strings.translateString("Undo")),new j({site:a.vaultItem})):(this.setAddText(),g=new j,a.defaultData.unencryptedUsername||g.showDetails({animate:!1}));else if(1===
a.matchingSites.length)a.generatedPasswordSaved?(g.text(Strings.translateString("Nice! We've updated your password")),this.nextButton.text(Strings.translateString("Got it")),this.backButton.LP_hide()):(g.text(Strings.translateString("Update password?")),this.nextButton.text(Strings.translateString("Update")),a.defaultData.unencryptedUsername||b.find(".addNewSiteButton").show()),a.vaultItem=LPProxy.getSiteModel(a.matchingSites[0]),new j({site:a.vaultItem});else{for(h=0;h<a.matchingSites.length;++h)(new j({site:LPProxy.getSiteModel(a.matchingSites[h])})).setSelectable(!0);
g.text(Strings.translateString("Which account should we update?"));a.defaultData.unencryptedUsername?this.hasDuplicates()&&f.text(Strings.translateString("Choose one to update and delete the duplicate.")):b.find(".addNewSiteButton").show();this.nextButton.text(Strings.translateString("Update"))}DialogWithGroupInput.prototype.setup.apply(this,arguments);this.inputFields.unencryptedUsername.setValues(LPProxy.getSiteUsernames());this.inputFields.unencryptedUsername.disableClickToggle()};SiteDialog.prototype.validate=
function(b){var a=DialogWithGroupInput.prototype.validate.apply(this,arguments);""===b.unencryptedUsername&&(this.addError("unencryptedUsername",Strings.translateString("Please enter a username.")),a=!1);return a};SiteDialog.prototype.getDialogActions=function(){};SiteDialog.prototype.close=function(b){bg.LPTabState.clear();DialogWithGroupInput.prototype.close.apply(this,arguments)};SiteDialog.prototype.saveGeneratedPassword=function(b,a){var c;if(b.generatedPassword&&b.formSubmitted&&b.defaultData.unencryptedUsername)if(0===
b.matchingSites.length)c=$.extend(m(b,void 0,void 0),b.dialogData),(new Account).addFromDialog(c,this.getGroup(c),{success:function(c){b.vaultItem=c;b.generatedPasswordSaved=!0;a()}});else if(1===b.matchingSites.length){var e=LPProxy.getSiteModel(b.matchingSites[0]);c=$.extend(m(b,e,void 0),b.dialogData);e.saveFromDialog(c,this.getGroup(c),{success:function(c){b.vaultItem=c;b.generatedPasswordSaved=!0;a()}})}else a();else a()};SiteDialog.prototype.open=function(b){var a=this;this.saveGeneratedPassword(b,
function(){var c=function(c){b.favicon=c;DialogWithGroupInput.prototype.open.call(a,b)};bg.LPIcons.get({url:b.defaultData.url,square:!0,callback:function(a){if(a)c(a);else{var f=function(){bg.LPPlatform.getFavicon({url:b.defaultData.url,callback:c})};b.sameDomain?csTop.LPContentScriptTools.getFavicon(function(a){a?c(a):f()}):f()}}})})};SiteDialog.prototype.showInitial=function(){var b=this;b.requestAnimationFrame(function(a){b.show();b.$element.addClass("animate-enter").one("animationend",function(){b.$element.removeClass("animate-enter");
a()})})};var f=null,q=!1;SiteDialog.prototype.showInProcessOverlay=function(){if(this.submitted){var b=this.$element;b.addClass("inProcess").one("animationend",function(){b.addClass("waiting");setTimeout(function(){q=!0;f&&f()},500)})}};SiteDialog.prototype.hideInProcessOverlay=function(){};SiteDialog.prototype.closeOnSuccess=function(){if(this.submitted){var b=this,a=function(){b.$element.removeClass("waiting").addClass("success").one("animationend.success",function(){setTimeout(function(){b.close()},
500)})};q?a():f=function(){setTimeout(function(){a()},0)}}};SiteDialog.prototype.performValidate=function(b){var a=this;if(a.selectedTile)if(a.selectedTile===a.activeTile)a.activeTile.handleChange(function(c){var f=b.callback;b.callback=function(){var b=arguments;c({callback:function(){f&&f.apply(a,b)}})};DialogWithGroupInput.prototype.performValidate.call(a,b)});else{var c=b.callback;b.callback=function(b){b||a.selectedTile.showDetails();c&&c.apply(this,arguments)};DialogWithGroupInput.prototype.performValidate.call(a,
b)}};SiteDialog.prototype.getErrorOptions=function(){return{"static":!0,alignTop:!0,showErrorLabel:!1}};SiteDialog.prototype.submit=function(){1===this.tiles.length&&(this.selectedTile=this.tiles[0]);this.selectedTile.preSubmit();DialogWithGroupInput.prototype.submit.apply(this,arguments);this.vaultItem?this.sendTrackingEvent("update"):this.sendTrackingEvent("add")};SiteDialog.prototype.handleSubmit=function(){this.submitted=!0;DialogWithGroupInput.prototype.handleSubmit.apply(this,arguments)};SiteDialog.prototype.postSetup=
function(){DialogWithGroupInput.prototype.postSetup.apply(this,arguments);this.postSetupData=this.getData()};SiteDialog.prototype.getData=function(){var b=DialogWithGroupInput.prototype.getData.apply(this,arguments),a=this.postSetupData;if(a&&b.fields)for(var c=0;c<b.fields.length;++c){var e=b.fields[c];a.unencryptedUsername&&a.unencryptedUsername===e.value?e.value=b.unencryptedUsername:a.password&&a.password===e.value&&(e.value=b.password)}return b}})();
