(function(c){var j=null;c.getBackgroundInterface=function(){null===j&&(j=Interfaces.createInstance(Interfaces.BackgroundInterface,{source:window,direct:!0}));return j}})(LPPlatform);
(function(c,j){c.getFavicon=function(a){a.callback&&a.callback(null)};c.getBigIcons=function(a,d){var b=(d||"big")+"icons",c=opendb();createDataTable(c);if(c){var e=function(b,d){a(0<d.rows.length&&null!==d.rows.item(0).data?d.rows.item(0).data:"")};if(g_indexeddb){var g={rows:{item:function(a){return this[a]},length:0}};c.transaction("LastPassData","readonly").objectStore("LastPassData").openCursor(IDBKeyRange.only(db_prepend(g_username_hash)+"_"+b)).onsuccess=function(a){(a=a.target.result)?(g.rows[g.rows.length]=
a.value,g.rows.length++,a["continue"]()):e(null,g)}}else c.transaction(function(a){a.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),b],e,function(a,b){console_log(b)})})}};c.saveBigIcons=function(a,d){var b=(d||"big")+"icons",c=opendb();createDataTable(c);c&&(g_indexeddb?c.transaction("LastPassData","readwrite").objectStore("LastPassData").put({username_hash:db_prepend(g_username_hash),type:b,data:a,usertype:db_prepend(g_username_hash)+"_"+b}):
c.transaction(function(d){d.executeSql("REPLACE INTO LastPassData (username_hash, type, data) VALUES (?, ?, ?)",[db_prepend(g_username_hash),b,a],function(){console_log("server.js : inserted")},function(a,b){console_log(b)})}))};c.updateBigIcons=function(){};var l=function(a,d){for(var b in a){var c=d[b];c&&(c.group=a[b])}};c.refreshGroupNames=function(a){a&&(l(a.sites,g_sites),l(a.notes,g_securenotes),l(a.applications,g_applications))};c.useDialogWindows=function(){return Preferences.get("htmlindialog")};
var k={};c.openTabDialog=function(a,d){var b={createAccountSimple:!0},q=a+(d?"-"+JSON.stringify(d):""),e=k[q];if(e)e.activate();else{var g={dialogWindow:c.useDialogWindows()&&!(d&&d.virtualKeyboard)},e={url:getchromeurl("tabDialog.html?dialog="+a),loadHandler:function(b){b.getTop().LPTabDialog.openDialog(a,d,g);k[q]=b},closeHandler:function(){delete k[q]},tabId:d&&d.tabId?d.tabId:void 0};if(e.tabId)c.navigateTab(e);else if(g.dialogWindow&&!b[a]){var h=Preferences.get("dialogSizePrefs"),b=h[a];e.features=
{height:b?b.height:600,width:b?b.width:800,left:b?b.left:0,top:b?b.top:0};e.features.width>window.screen.availWidth&&(e.features.width=window.screen.availWidth,e.features.left=0);e.features.height>window.screen.availHeight&&(e.features.height=window.screen.availHeight,e.features.top=0);var j=e.closeHandler,f=function(b){h[a]={height:b.outerHeight,width:b.outerWidth,left:b.screenLeft||b.screenX,top:b.screenTop||b.screenY};Preferences.set("dialogSizePrefs",h);delete k[q]};e.closeHandler=function(){j.apply(this,
arguments);f.apply(this,arguments)};c.openDialogWindow(e)}else if(b[a])c.openTab(e);else switch(Preferences.get("openpref")){case "tabs":c.openTab(e);break;case "windows":c.openWindow(e);break;case "same":c.openSame(e)}}};c.stringifyFeatures=function(a){var d=[],b;for(b in a)d.push(b+"="+a[b]);return d.join(",")};c.doAjax=function(a){LPServer.ajax(a)};c.ajax=function(a){isOffline()?a.error&&a.error(null,null,"offline"):c.doAjax(a)};c.isEdge=function(){return is_edge()};c.copyDataIfEdge=function(a){return c.isEdge()&&
"undefined"!==typeof a?JSON.parse(JSON.stringify(a)):a};var t=c.setUserPreference;c.setUserPreference=function(a,d){t(a,d);g_userprefs_changed[a]=d};var u=c.setGlobalPreference;c.setGlobalPreference=function(a,d){u(a,d);g_gblprefs_changed[a]=d};c.writePreferences=function(){lpWriteAllPrefs()};c.closePopovers=function(){};var n={},r={},p={},h={};j.LPTabs={get:function(a){if(a.interface){var d=[],b;for(b in h)h[b].tabDetails.interfaceName===a.interface&&d.push(h[b]);return d}if("undefined"!==typeof a.tabID){if(d=
h[a.tabID])return a.callback&&a.callback(d),d;a.callback&&((d=p[a.tabID])||(d=p[a.tabID]=[]),d.push(a.callback))}}};c.initializeRequestFramework=function(a){var d=h[a.tabID],b={tabURL:a.tabURL,tabID:a.tabID,windowID:a.windowID},c=LPMessaging.getNewMessageSourceID(),e=!1,g=function(b){try{return b.frameID=c,a.sendContentScript(b)}catch(d){return!1}},j=function(a){return g({type:"backgroundResponse",data:a})},k=function(){delete n[c];var a=h[b.tabID];a&&(a.removeFrame(c),a.isEmpty()&&(delete h[b.tabID],
delete r[b.tabID]))};return{frameID:c,requestHandler:function(f){switch(f.type){case "backgroundRequest":LPMessaging.handleRequest(Interfaces.BackgroundInterface,f.data,j,{additionalArguments:{tabURL:b.tabURL,tabID:b.tabID,windowID:b.windowID,frameID:c,top:e}});break;case "contentScriptRequest":case "contentScriptResponse":if(0===f.frameID)LPMessaging.handleResponse(f.data);else if(f.frameID){var m=n[f.frameID];m&&m(f)}break;case "initialize":f=f.data;(e=f.top)&&"undefined"!==typeof b.tabID&&(r[b.tabID]=
c);g({type:"initialization",data:{tabID:b.tabID,frameID:c,topFrameID:r[b.tabID],request:f}});if(f.extendFrame){var l=n[c];n[f.extendFrame]=function(a){contentScriptSender(a);l(a)}}else n[c]=g;if(f.interfaceName&&Interfaces.hasOwnProperty(f.interfaceName)){b.interfaceName||(b.interfaceName=f.interfaceName);var m=function(a){return LPMessaging.makeRequest(g,{type:"contentScriptRequest",sourceFrameID:0,data:a})},s=Interfaces.createInstance(Interfaces[f.interfaceName],{instance:f.extendFrame?d.getTop():
null,direct:!1,context:a.context||"background",requestFunction:m});"number"===typeof b.tabID&&f.interfaceName===b.interfaceName&&!f.extendFrame&&(d||(d=h[b.tabID]=new LPTab(b)),d.addFrame(s,{topWindow:e,frameID:c,contentScriptRequester:m}));a.callback&&a.callback(s)}break;case "disconnect":k();break;case "initialized":e&&p[b.tabID]&&(p[b.tabID].forEach(function(a){a(d)}),delete p[b.tabID])}},disconnectHandler:k}}})(LPPlatform,this);
