// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2016 Vlad & Serge Strukoff. All Rights Reserved.
chrome.runtime.onStartup.addListener(function(){});
(function(){function k(){chrome.runtime.onMessage.addListener(J);b.p26&&chrome.windows.onRemoved.addListener(K);b.p29&&z(1);b.p30&&A(1);b.p32&&B(1);chrome.browserAction.onClicked.addListener(function(){p("cleaner.html",!0,770,500)});setTimeout(C,2107)}function q(a){if(3==b.nv)D(1);else if("8.9.3"!==b.ver){var e=f;b.nv=Math.floor(Math.random()*(e+19872E5-e+1))+e;b.ver="8.9.3";g();setTimeout(C,1912)}else 0<b.nv&&b.nv<f&&D();a?E(a,1,function(){}):b.p31&&6048E5<f-b.lr&&p("cleaner.html",!0,770,500)}function g(){localStorage.setItem("opt",
JSON.stringify(b))}function D(a){b.nv=0;g();F(function(b){b&&r(a?"http://www.hotcleaner.com/clickclean/install-clickclean.html":"http://www.hotcleaner.com/clickclean_chrome.html#chnijda",a?!1:!0);L({ea:a?"install":"update"})})}function K(a){a==t?t=-9:chrome.windows.getAll({},function(a){a&&0==a.length&&setTimeout(G,500)})}function G(){chrome.windows.create({url:"cc.html",type:"popup",top:20,left:screen.width-340,width:300,height:48},function(a){t=a.id})}function M(a,b){if(7978==a.menuItemId)chrome.history.deleteUrl({url:b.url},
function(){N(b.url,function(){chrome.tabs.executeScript(b.id,{file:"safe.js"})})});else if(7979==a.menuItemId){var c=a.linkUrl,d=c.indexOf("&url="),h;0<d&&(h=c.indexOf("&",d+5),c=decodeURIComponent(c.slice(d+5,h)));chrome.tabs.create({url:c})}else 7980==a.menuItemId&&chrome.tabs.create({url:"https://encrypted.google.com/search?q="+encodeURIComponent(a.selectionText)+"&tbo=1"})}function z(a){chrome.contextMenus.removeAll();a&&(a=chrome.i18n.getMessage("ctxMenu").split(";"),chrome.contextMenus.create({id:"7978",
title:a[0],contexts:["page"]}),chrome.contextMenus.create({id:"7979",title:a[1],contexts:["link"]}),chrome.contextMenus.create({id:"7980",title:a[2],contexts:["selection"]}),chrome.contextMenus.onClicked.addListener(M))}function A(a){chrome.tabs.onCreated[a?"addListener":"removeListener"](H);chrome.tabs.onUpdated[a?"addListener":"removeListener"](H)}function I(a){chrome.browserAction.setTitle({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"});chrome.browserAction.setBadgeBackgroundColor({color:50<
a?[255,0,0,255]:[0,162,241,255]});chrome.browserAction.setBadgeText({text:0<a?99<a?"99+":a.toString():""})}function l(){chrome.history.search({text:""},function(a){a&&-1<a.length&&I(a.length)})}function B(a){chrome.history.onVisited[a?"addListener":"removeListener"](l);chrome.history.onVisitRemoved[a?"addListener":"removeListener"](l);a?l():I(0)}function N(a,b){function c(){h++;h<d.length?chrome.cookies.remove({url:a,name:d[h].name},c):b()}var d,h=-1;chrome.cookies.getAll({url:a},function(a){d=a;
c()})}function H(a,b,c){a=c?c:a;b=a.url;0==b.indexOf(u)&&7<b.indexOf("/history/")&&chrome.tabs.update(a.id,{url:"chrome-search://local-ntp/local-ntp.html"})}function O(a,b){F(function(c){r(c?a:b)})}function r(a,b){function c(a){chrome.windows.update(a.windowId,{focused:!0})}chrome.tabs.query({url:a},function(d){if(d&&d.length)chrome.tabs.update(d[0].id,{active:!0},c);else if(b)try{chrome.windows.create({url:a,focused:!0,incognito:!0,state:"maximized"},function(){chrome.runtime.lastError&&chrome.tabs.create({url:a,
active:!0},c)})}catch(h){chrome.tabs.create({url:a,active:!0},c)}else chrome.tabs.create({url:a,active:!0},c)})}function p(a,b,c,d){a=b?chrome.runtime.getURL(a):a;chrome.tabs.query({url:a},function(b){if(b&&0<b.length)chrome.windows.update(b[0].windowId,{focused:!0});else{var e=window.devicePixelRatio||1;b=screen.width;var f=screen.height-70,g=parseInt(d*e),e=parseInt(c*e),k=parseInt((b-e)/2),l=parseInt((f-g)/2);e>b&&(e=b,k=0);g>f&&(g=f,l=0);0>k&&(k=0);0>l&&(l=0);chrome.windows.create({type:"popup",
focused:!0,url:a,top:l,left:k,width:e,height:g})}})}function J(a,e,c){try{a=JSON.parse(a)}catch(h){return}var d=a.id;0==d?p(a.url,a.local,a.w,a.h):1==d?(d=0,!b.p26&&b.p31&&(6048E5<f-b.lr&&(d=1),b.lr=f,g()),c({v:b,u:e.tab.url,t:f,n:d})):2==d?c(e.tab.url):3==d?c(b):4==d?G():5==d?m("GET",a.v,null,"blob",function(b){if(a.v1){var d=new FileReader;d.onload=function(a){c(a.target.result)};d.readAsDataURL(b)}else{window.URL=window.URL||window.webkitURL;var e=window.URL.createObjectURL(b);c(e);setTimeout(function(){window.URL.revokeObjectURL(e)},
1E3)}}):7==d?(b.p29!=a.v.p29?z(a.v.p29):b.p30!=a.v.p30?A(a.v.p30):b.p32!=a.v.p32&&B(a.v.p32),b=a.v,g()):8==d?O(a.v,a.v3):9==d?r(a.v,a.i):10==d?chrome.history.deleteUrl(a.v,c):11==d?chrome.history.deleteRange(a.v,c):12==d?chrome.history.search(a.v,c):13==d?chrome.history.getVisits(a.v,c):14==d?chrome.tabs.update(e.tab.id,{url:"chrome://"==u?"chrome-search://local-ntp/local-ntp.html":u+"newtab"},function(){chrome.history.deleteUrl(a.v)}):15==d?m("POST","http://localhost:27077/mc/"+a.v,a.v2?a.v2:null,
0,function(a){c(a)}):18==d?(e=w(),E(e,0,c)):19==d?(0>a.v.since&&(a.v.since=w()),a.v2.cookies?(x(),c(b.p28)):chrome.browsingData.remove(a.v,a.v2,function(){c(b.p28)})):30==d?P(c):31==d?x():32==d?Q(a.v):34==d?c(n("wl",Array)||[]):35==d?localStorage.setItem("wl",JSON.stringify(a.v)):37==d?R(a.v):700==d&&(b.ui=a.v,g());return!0}function E(a,e,c){b.p4&&x();if(b.dev){var d,h;b.p20&&(h=y("st")||f,d=n("wl",Array)||[]);chrome.browsingData.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,
formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,pluginData:!!b.p12,serverBoundCertificates:e?!1:!!b.p4},function(){chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!0,extension:!1}},{cookies:!!b.p13,localStorage:!!b.p14,webSQL:!!b.p15,indexedDB:!!b.p16,fileSystems:!!b.p17,appcache:!!b.p18},function(){chrome.browsingData.remove({since:a,originTypes:{unprotectedWeb:!1,protectedWeb:!1,extension:!0}},{cookies:!!b.p19,
localStorage:!!b.p20,webSQL:!!b.p21,indexedDB:!!b.p22,fileSystems:!!b.p23,appcache:!!b.p24},function(){b.p19&&(document.cookie="s=1; expires=0; path=/");b.p20&&(localStorage.st=h,localStorage.setItem("opt",JSON.stringify(b)),localStorage.setItem("wl",JSON.stringify(d)));b.p32&&l();c()})})})}else chrome.browsingData.remove({since:a},{history:!!b.p1,downloads:!!b.p2,cache:!!b.p3,passwords:!!b.p5,formData:!!b.p6,localStorage:!!b.p7,webSQL:!!b.p8,indexedDB:!!b.p9,fileSystems:!!b.p10,appcache:!!b.p11,
pluginData:!!b.p12,serverBoundCertificates:e?!1:!!b.p4},function(){b.p32&&l();c()})}function Q(a){var b;a.forEach(function(a){chrome.cookies.getAll({domain:a},function(d){d.forEach(function(d){b=d.domain;"."==b.charAt(0)&&(b=b.slice(1));b==a&&chrome.cookies.remove({url:"http"+(d.secure?"s":"")+"://"+b+d.path,name:d.name})})})})}function R(a){chrome.cookies.getAll({url:a},function(a){a.forEach(function(a){chrome.cookies.remove({url:"http"+(a.secure?"s":"")+"://"+a.domain+a.path,name:a.name},function(a){})})})}
function x(a){var b=a?a:n("wl",Array)||[],c;chrome.cookies.getAll({},function(a){a.forEach(function(a){c=a.domain;"."==c.charAt(0)&&(c=c.slice(1));0>b.indexOf(c)&&chrome.cookies.remove({url:"http"+(a.secure?"s":"")+"://"+c+a.path,name:a.name})})})}function P(a){var b=n("wl",Array)||[],c=[];chrome.cookies.getAll({},function(d){for(var h=0,f;f=d[h];h++)c.push(f.domain);a([c,b])})}function w(){var a=b.timeType;return 10==a?1:0==a?f:9==a?b.time:Date.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function F(a){var b=
new Image;b.onload=function(){a(1)};b.onerror=function(){a()};b.onabort=function(){a()};b.src="http://www.hotcleaner.com/img/1.gif?t="+(new Date).getTime()}function C(){m("GET","manifest.json",null,"text",function(a){if(a){try{a=JSON.parse(a)}catch(b){return}m("GET",a.update_url+"?x=id%3Dghgabhipcejejjmhhchfonmamedcbeod%26v%3D"+a.version+"%26uc",null,"text",function(){})}})}function L(a){var e=a.ec?a.ec:"app",c=a.ea?a.ea:"unk";a=a.el?a.el:"CC 8.9.3";b.uid||(b.uid=S());m("POST","http://www.google-analytics.com/collect",
"v=1&tid=UA-326771-6&cid="+b.uid+"&t=event&ec="+e+"&ea="+c+"&el="+a,"text",function(){})}function m(a,b,c,d,f){var g=new XMLHttpRequest;g.open(a,b,!0);d&&(g.responseType=d);g.onload=function(a){200==this.status?f(this.response):f(null)};g.onerror=function(){f(null)};g.onabort=function(){f(null)};g.send(c)}function S(){var a=Math.random,b=(4294967296*a()>>>0).toString(16),c=((4294967296*a()&4294922239|16384)>>>0).toString(16),d=((4294967296*a()&3221225471|2147483648)>>>0).toString(16),a=(4294967296*
a()>>>0).toString(16);8>b.length&&(b=("0000000"+b).slice(-8));8>c.length&&(c=("0000000"+c).slice(-8));8>d.length&&(d=("0000000"+d).slice(-8));8>a.length&&(a=("0000000"+a).slice(-8));return[b,c.slice(0,4),c.slice(4),d.slice(0,4),d.slice(4)+a].join("-")}function y(a){a=parseInt(localStorage[a]);return isNaN(a)?null:a}function n(a,b){try{v=JSON.parse(localStorage[a])}catch(c){v=null}return null===v||v.constructor!==b?null:v}var f=Date.now(),u=/Comodo/.test(navigator.appVersion)?"dragon://":"chrome://",
b,t;(function(){try{chrome.runtime.setUninstallURL("http://www.hotcleaner.com/security-and-privacy-software-feedback.html#chuijda")}catch(h){}var a={ver:"8.9.3",lr:f,nv:3,uid:"",timeType:10,time:0,dev:0,ui:700,p0:0,p1:1,p2:1,p3:1,p4:0,p5:0,p6:1,p7:0,p8:1,p9:1,p10:1,p11:1,p12:1,p13:0,p14:0,p15:0,p16:0,p17:0,p18:0,p19:0,p20:0,p21:0,p22:0,p23:0,p24:0,p25:0,p26:0,p27:0,p28:1,p29:0,p30:0,p31:1,p32:1},e;b=n("opt",Object);if(null===b||void 0===b.ver)b=a,e=!0;else{for(var c in b)c in a?typeof b[c]!==typeof a[c]&&
(b[c]=a[c],e=!0):(delete b[c],e=!0);for(c in a)c in b||(b[c]=a[c],e=!0)}e&&g();if(document.cookie&&-1<document.cookie.indexOf("s=1"))f=y("st")||f,k();else{document.cookie="s=1; expires=0; path=/";var d;b.p26&&(d=0==b.timeType?y("st")||f:w());localStorage.st=f;k();q(d)}})()})();function copyToClipboard(k,q){if(!q||prompt("Copy to clipboard",k)){var g=document.createElement("textarea");g.value=k;document.body.appendChild(g);g.select();document.execCommand("Copy");document.body.removeChild(g)}};
