// Calendar Control - MIT, 2016 Vlad & Serge Strukoff
var CALCONF={},CALTOKENS=[],CALTOKENS_IDX={};
function calInit(a,c,b,d){var f=chrome.i18n.getMessage("calendar").split(";");CALCONF.months=f.slice(0,12);CALCONF.weekdays=f.slice(12,19);CALCONF.longwdays=f.slice(19,26);CALCONF.weekstart=0;CALCONF.prevyear=f[26];CALCONF.nextyear=f[27];CALCONF.prevmonth=f[28];CALCONF.nextmonth=f[29];CALCONF.today=f[30];CALCONF.cancel=f[31];CALTOKENS.push({t:"l",r:CALCONF.longwdays.join("|"),p:function(a,b){return a},g:function(a){return CALCONF.longwdays[a.getDay()]}},{t:"Y",r:"19\\d{2}|20\\d{2}",p:function(a,b){a.setFullYear(Number(b));
return a},g:function(a){return a.getFullYear()}},{t:"F",r:CALCONF.months.join("|"),p:function(a,b){for(var c=0;12>c;c++)if(CALCONF.months[c]==b)return a.setMonth(c),a},g:function(a){return CALCONF.months[a.getMonth()]}},{t:"d",r:"0[1-9]|[12][0-9]|3[01]",p:function(a,b){a.setDate(Number(b));a.getDate()!=b&&a.setDate(0);return a},g:function(a){a=a.getDate();return(10>a?"0":"")+a}},{t:"h",r:"[0-1][0-9]|2[0-3]",p:function(a,b){a.setHours(Number(b));a.getHours()!=b&&a.setHours(0);return a},g:function(a){a=
a.getHours();return(10>a?"0":"")+a}},{t:"e",r:"[0-4][0-9]|5[0-9]",p:function(a,b){a.setMinutes(Number(b));a.getMinutes()!=b&&a.setMinutes(0);return a},g:function(a){a=a.getMinutes();return(10>a?"0":"")+a}},{t:"s",r:"[0-4][0-9]|5[0-9]",p:function(a,b){a.setSeconds(Number(b));a.getSeconds()!=b&&a.setSeconds(0);return a},g:function(a){a=a.getSeconds();return(10>a?"0":"")+a}});for(f=0;f<CALTOKENS.length;f++)CALTOKENS_IDX[CALTOKENS[f].t]=CALTOKENS[f];a.onDateChanged=d;a.showTime=b;calSetDate(a,c?new Date(c):
new Date);a.oncut=function(a){a.preventDefault()};a.oncontextmenu=function(a){a.preventDefault()};a.ondragstart=function(a){a.preventDefault()};a.onkeydown=function(a){this.nextElementSibling.focus();a.preventDefault()};a.onclick=function(a){a.preventDefault()};a.addEventListener("mouseup",calMouseup,!1);b&&(a.nextElementSibling.addEventListener("mousedown",calOnSpinDown,!1),a.nextElementSibling.addEventListener("mouseup",calOnSpinUp,!1),a.nextElementSibling.nextElementSibling.addEventListener("mousedown",
calOnSpinDown,!1),a.nextElementSibling.nextElementSibling.addEventListener("mouseup",calOnSpinUp,!1))}function calSetDate(a,c){a.showTime||(c=calResetTime(c));var b=c.getTime();a.setAttribute("data-time",b);a.value=calGenerateDate(c,a.getAttribute("data-format"));a.onDateChanged(b)}function calClose(){$("cal").style.display="none"}function calSetToday(a){calSetDate(this.parentElement.e_input,new Date);calClose()}
function calParseDate(a,c){for(var b,d="^",f={},n=0,k=0;k<c.length;k++)b=c.charAt(k),CALTOKENS_IDX[b]?(f[b]=++n,d+="("+CALTOKENS_IDX[b].r+")"):d=" "==b?d+"\\s":d+((b.match(/[\w\d]/)?"":"\\")+b);if(!a.match(new RegExp(d+"$")))return 0;d=new Date;d.setDate(1);for(k=0;k<CALTOKENS.length;k++)b=CALTOKENS[k].t,f[b]&&(b=RegExp["$"+f[b]],d=CALTOKENS[k].p(d,b));return d}
function calGetHTML(a){function c(a,b,c,d){var e=document.createElement("button");b&&(e.className=b);e.textContent=c;a.appendChild(e);e.addEventListener("click",d,!1)}function b(a,b){var c=document.createElement("div");c.className="arrow"+(b?"Left":"Right");c.style.display="inline-block";a.appendChild(c)}var d=$("cal"),f=d.e_input,n=f.getAttribute("data-format"),k=new Date,n=calParseDate(f.value,n);a||(a=n);f.showTime||(a=calResetTime(a));f=new Date(a);f.setDate(1);f.setDate(1-(7+f.getDay()-CALCONF.weekstart)%
7);var g,p=document.createDocumentFragment(),m,h,e;m=document.createElement("table");m.id="calCtrls";h=document.createElement("tr");m.appendChild(h);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.prevyear;e.time=calRelDate(a,-1,"FullYear");e.addEventListener("click",calUpdate,!1);h.appendChild(e);b(e,1);b(e,1);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.prevmonth;e.time=calRelDate(a,-1,"Month");e.addEventListener("click",calUpdate,!1);h.appendChild(e);
b(e,1);e=document.createElement("th");e.textContent=CALCONF.months[a.getMonth()]+" "+a.getFullYear();h.appendChild(e);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.nextmonth;e.time=calRelDate(a,1,"Month");e.addEventListener("click",calUpdate,!1);h.appendChild(e);b(e,0);e=document.createElement("td");e.className="calCtrl";e.title=CALCONF.nextyear;e.time=calRelDate(a,1,"FullYear");e.addEventListener("click",calUpdate,!1);h.appendChild(e);b(e,0);b(e,0);p.appendChild(m);m=document.createElement("table");
m.id="calGrid";h=document.createElement("tr");m.appendChild(h);for(g=0;7>g;g++)e=document.createElement("th"),e.textContent=CALCONF.weekdays[(CALCONF.weekstart+g)%7],h.appendChild(e);for(var q,r,l=new Date(f);l.getMonth()==a.getMonth()||l.getMonth()==f.getMonth();){h=document.createElement("tr");for(var t=0;7>t;t++){g=[];q=l.getDate();e=l.getMonth();r=l.getYear();l.getMonth()!=a.getMonth()&&(g[g.length]="calOtherMonth");if(0==l.getDay()||6==l.getDay())g[g.length]="calWeekend";r==k.getYear()&&e==k.getMonth()&&
q==k.getDate()&&(g[g.length]="calToday");r==n.getYear()&&e==n.getMonth()&&q==n.getDate()&&(g[g.length]="calSelected");e=document.createElement("td");e.textContent=q;e.className=g.join(" ");e.time=calRelDate(l);h.appendChild(e);e.addEventListener("click",calUpdate,!1);l.setDate(++q)}m.appendChild(h)}p.appendChild(m);c(p,"calBtn",CALCONF.today,calSetToday);c(p,"calBtn",CALCONF.cancel,calClose);d.innerHTML="";d.appendChild(p)}
function calRelDate(a,c,b){var d=new Date(a);c&&(d["set"+b](a["get"+b]()+c),d.getDate()!=a.getDate()&&d.setDate(0));return d.valueOf()}function calUpdate(a){a=document.getElementById("cal");var c=a.e_input,b=this.time,d=new Date(b);"calCtrl"==this.className?calGetHTML(d,a):(c.value=calGenerateDate(d,c.getAttribute("data-format")),c.setAttribute("data-time",b),c.onDateChanged(b),a.style.display="none")}
function calOnDateChanged(a){var c=calParseDate(a.value,a.getAttribute("data-format"));a.onDateChanged(c.getTime())}function calGenerateDate(a,c){for(var b,d="",f=0;f<c.length;f++)b=c.charAt(f),d+=CALTOKENS_IDX[b]?CALTOKENS_IDX[b].g(a):b;return d}function calOnSpinDown(a){a=this.parentElement.firstElementChild;a.repeat=1E3;a.up="calUp"==this.className?1:0;calOnSpin(a)}function calOnSpinUp(){var a=this.parentElement.firstElementChild;a.repeat=0;calOnDateChanged(a)}
function calOnSpin(a){var c=a.repeat;if(c){1E3==c?c-=801:200>c&&(c-=25);100>c&&(c=100);a.repeat=c;var b=a.value.indexOf("-");a.selStart||(a.selStart=b+2);var d=a.value.slice(a.selStart,a.selStart+2),d="0"==d.charAt(0)?parseInt(d.charAt(1)):parseInt(d);a.up?d+=1:--d;a.selStart==b+2?23<d?d="00":0>d?d="23":10>d&&(d="0"+d):59<d?d="00":0>d?d="59":10>d&&(d="0"+d);a.value=a.value.slice(0,a.selStart)+d+a.value.slice(a.selStart+2);setTimeout(calOnSpin,c,a)}}
function calOnTime(a){var c=a.value.indexOf("-"),b=a.selectionStart;if(b>c)return b<c+5?b=c+2:b<c+8?b=c+5:b<c+12&&(b=c+8),a.selStart=b,a.setSelectionRange(b,b+2),1;a.setSelectionRange(0,c-1);return 0}
function calMouseup(a){a=document.getElementById("cal");var c=$XY(this);a||(a=document.createElement("button"),a.onselectstart=function(){return!1},a.id="cal",document.body.appendChild(a));if(this.showTime){if(calOnTime(this)){a.style.display="none";return}}else this.blur();0<a.offsetHeight&&a.e_input==this?a.style.display="none":(a.e_input=this,a.style.display="block",calGetHTML(0,a),a.style.top=c[1]+this.offsetHeight+"px",a.style.left=c[0]+"px",a.style.display="block",a.focus())}
function calResetTime(a){a.setHours(0);a.setMinutes(0);a.setSeconds(0);a.setMilliseconds(0);return a}function $XY(a){if(a&&void 0!=a){var c=0,b=0;if(a.offsetParent){do c+=a.offsetLeft,b+=a.offsetTop;while(a=a.offsetParent)}return[c,b]}}function $(a){return document.getElementById(a)};
