// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2016 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function N(a){O(a.u);f=a.v;x=a.t;u();var b,c,d;document.title=chrome.i18n.getMessage("m2");P();b=chrome.i18n.getMessage("cleaner2").split(";");d=document.getElementsByClassName("section");for(var e=0;3>e;e++)d[e].childNodes[0].textContent=b[e];d=document.getElementsByClassName("subtitle");for(e=0;3>e;e++)d[e].textContent=b[e+3];d=g("timeType");b=chrome.i18n.getMessage("cleaner3").split(";");g("timeLabel").textContent=b[0];for(e=1;12>e;e++)c=document.createElement("option"),c.textContent=
b[e],d.appendChild(c);d.selectedIndex=f.timeType;d.addEventListener("change",y,!1);E();b=chrome.i18n.getMessage("cleaner4").split(";");c=chrome.i18n.getMessage("cleaner5").split(";");for(e=0;33>e;e++){d=g("p"+e);f[d.id]&&d.setAttribute("on",!0);d.addEventListener("click",Q,!1);d=d.nextElementSibling;"optMore"==d.className&&(d.title=c[0],d.addEventListener("click",R,!1),d=d.nextElementSibling);if("optRun"==d.className||"optDel"==d.className)d.title=0==e?c[1]:25==e?c[2]:26==e?c[3]:27==e?c[4]:28==e?
c[5]:b[e],d.addEventListener("click",S,!1),d=d.nextElementSibling;d.textContent=d.title=b[e]}document.body.addEventListener("mousedown",function(a){"select"!=a.target.localName&&"input"!=a.target.localName&&"p"!=a.target.localName&&a.preventDefault()},!1);b=document.getElementsByTagName("label");e=0;for(d=b.length;e<d;e++)b[e].addEventListener("mouseup",function(a){this.control&&setTimeout(function(){a.target.control.blur()},100)},!1);T();document.body.style.display="block";d=g("timeType");d.style.width=
F(d.value)+40+"px";a.n&&p("m3",function(){m("http://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("history.html"))},0,0,"b2",0,"rgba(255,255,255,.75)");U()}function q(){chrome.runtime.sendMessage(JSON.stringify({id:7,v:f}))}function T(){chrome.tabs.getCurrent(function(a){var b=chrome.runtime.getURL("cleaner.html");chrome.tabs.query({url:b},function(b){for(var d=0,e=b.length;d<e;d++)b[d].id!=a.id&&chrome.tabs.remove(b[d].id);chrome.windows.getCurrent({},function(b){var c=window.devicePixelRatio||
1,d=screen.width,e=screen.height-70,f=parseInt(500*c),c=parseInt(770*c),g=parseInt((d-c)/2),h=parseInt((e-f)/2);c>d&&(c=d,g=0,document.body.style.zoom=window.innerWidth/850);f>e&&(f=e,h=0);0>g&&(g=0);0>h&&(h=0);"normal"==b.type?chrome.windows.create({type:"popup",focused:!0,tabId:a.id,top:h,left:g,width:c,height:f}):chrome.windows.update(b.id,{state:"normal",width:c,height:f})})})})}function U(){/Win/.test(navigator.platform)?chrome.runtime.sendMessage('{"id":15,"v":"000E"}',function(a){z=a?1:2}):
z=3}function S(a){a=this.parentElement.firstElementChild.id;"p5"!=a||f[a]?"p20"!=a||f[a]?A(a):p("m20b",A,r,a):p("m5b",A,r,a)}function A(a){function b(){d.className="ghk";h(!1,!1);G();(28==a||f.p28)&&H();l(0==a||25==a||28==a?"m8":"m7",500);setTimeout(function(){d.className="chk"},500)}l();h(!0,!0);var c=I(),d=g(a);a=a.slice(1);27==a&&J();d.className="wipe";28==a?b():K(a,c,b)}function V(){function a(a){for(var b,c=0,d=k.length;c<d;c++)b=g("p"+k[c]),b.hasAttribute("on")&&(b.className=a)}function b(){f.p28&&
H();l("m7",1E3);G();setTimeout(function(){a("chk");h(!1,0);f.p27&&J()},1E3)}function c(){setTimeout(function(){g("p"+k[w]).className="ghk";d()},10)}function d(){w++;if(w<k.length){var a=k[w];f["p"+a]?K(a,e,c):d()}else b()}h(!0,!0);l();var e=I(),w=-1,k;k=f.dev?[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]:[0,1,2,3,4,5,6,7,8,9,10,11,12,25];a("wipe");d()}function K(a,b,c){var d=chrome.browsingData,e={since:b};if(13>a)0==a?L(0,c):1==a?d.removeHistory(e,c):2==a?d.removeDownloads(e,
function(){d.removeDownloads(e,c)}):3==a?d.removeCache(e,c):4==a?d.remove(e,{serverBoundCertificates:!0},function(){chrome.runtime.sendMessage('{"id":31}');c()}):5==a?d.removePasswords(e,c):6==a?d.removeFormData(e,c):7==a?d.removeLocalStorage(e,c):8==a?d.removeWebSQL(e,c):9==a?d.removeIndexedDB(e,c):10==a?d.removeFileSystems(e,c):11==a?d.removeAppcache(e,c):12==a&&d.removePluginData(e,c);else if(19>a)e.originTypes={unprotectedWeb:!1,protectedWeb:!0,extension:!1},13==a?d.removeCookies(e,c):14==a?d.removeLocalStorage(e,
c):15==a?d.removeWebSQL(e,c):16==a?d.removeIndexedDB(e,c):17==a?d.removeFileSystems(e,c):18==a&&d.removeAppcache(e,c);else if(25>a)if(e.originTypes={unprotectedWeb:!1,protectedWeb:!1,extension:!0},19==a)d.removeCookies(e,function(){document.cookie="s=1; expires=0; path=/";c()});else if(20==a){var g=W("wl",Array)||[];d.removeLocalStorage(e,function(){localStorage.st=x;localStorage.setItem("opt",JSON.stringify(f));localStorage.setItem("wl",JSON.stringify(g));c()})}else 21==a?d.removeWebSQL(e,c):22==
a?d.removeIndexedDB(e,c):23==a?d.removeFileSystems(e,c):24==a&&d.removeAppcache(e,c);else 25==a?L(1,c):c()}function L(a,b){chrome.tabs.getCurrent(function(c){chrome.tabs.query(a?{active:!0}:{},function(d){var e=0;d.forEach(function(b,d){c.id==b.id?0==d&&e++:a?chrome.tabs.reload(b.id):d>e?chrome.tabs.remove(b.id):chrome.tabs.update(b.id,{url:"chrome-search://local-ntp/local-ntp.html"})});b&&setTimeout(b,500)})})}function J(){chrome.tabs.getCurrent(function(a){chrome.tabs.remove(a.id)})}function G(){chrome.history.search({text:""},
function(a){a&&-1<a.length&&(a=a.length,chrome.browserAction.setTitle({title:0<a?"Visited Pages: "+a+"\nClick&Clean":"\nClick&Clean"}),chrome.browserAction.setBadgeBackgroundColor({color:50<a?[255,0,0,255]:[0,162,241,255]}),chrome.browserAction.setBadgeText({text:0<a?99<a?"99+":a.toString():""}))})}function R(a){a=parseInt(this.previousElementSibling.id.slice(1));var b=[7,8,9,10,13,14,15,16,17,19,20,21,22,23],c=/Comodo/.test(navigator.appVersion)?"dragon://":/OPR/.test(navigator.appVersion)?"opera://":
"chrome://";if(1==a)m("http://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("history.html"));else{if(2==a)c+="downloads/";else if(3==a){if(1==z){m("http://www.hotcleaner.com/cache-viewer.html",chrome.runtime.getURL("cache.html"));return}c+="view-http-cache"}else{if(4==a){m("http://www.hotcleaner.com/cookie-wiper.html",chrome.runtime.getURL("cookies.html"));return}-1<b.indexOf(a)?c+="settings/cookies":5==a?c+="settings/passwords":6==a?c+="settings/autofill":11==a||18==a||24==
a?c+="appcache-internals":12==a?c+="plugins":26==a&&(c+="version")}chrome.runtime.sendMessage(JSON.stringify({id:9,v:c}))}}function F(a){var b=g("textMetrics");b.textContent=a;return b.offsetWidth}function X(a){f.time=a;q()}function y(){var a=g("timeType");f.timeType=a.selectedIndex;a.style.width=F(a.value)+40+"px";E();q()}function E(){var a=g("time");if(9==f.timeType)a.firstElementChild.hasAttribute("data-time")||calInit(a.firstElementChild,f.time,1,X),a.style.display="",g("timeType").style.width=
"1px";else if(a.style.display="none",a=g("cal"))a.style.display="none"}function I(){var a=f.timeType;return 10==a?1:0==a?x:9==a?f.time:Date.now()-36E5*[0,1,2,4,8,10,12,24,168][a]}function Q(a){a=this.id;"p5"!=a||f[a]?"p20"!=a||f[a]?B(a):p("m20a",B,r,a):p("m5a",B,r,a)}function B(a){var b=g(a);b.hasAttribute("on")?(b.removeAttribute("on"),f[a]=0):(b.setAttribute("on",!0),f[a]=1);q()}function h(a,b,c){var d=g("shade"),e=g("clear");e.disabled=g("reset0").disabled=g("reset1").disabled=g("reset2").disabled=
g("dev").disabled=a;d.style.backgroundColor=c?c:"";d.style.height=a?g("tab").scrollHeight+"px":"";b?e.setAttribute("on",!0):e.removeAttribute("on")}function l(a,b){var c=g("msg");a?(c.textContent=chrome.i18n.getMessage(a)+"!",c.style.top="48px",c.t&&(clearTimeout(c.t),c.t=null),c.t=setTimeout(l,b)):c.style.top=""}function p(a,b,c,d,e,f,k){function l(){p();b(d)}function n(){p();c(d)}function p(){m.style.display="";window.removeEventListener("resize",r,!1);b&&q.removeEventListener("click",l,!1);c&&
t.removeEventListener("click",n,!1);h(!1)}function r(){m.style.top=(document.body.offsetHeight-m.offsetHeight)/2+"px"}h(!0,!1,k?k:"rgba(0,0,0,.3)");var m=g("alert");k=m.firstElementChild.nextElementSibling;var t=k.nextElementSibling.firstElementChild,q=t.nextElementSibling;k.textContent=chrome.i18n.getMessage(a);q.textContent=chrome.i18n.getMessage(e?e:"b0");t.textContent=chrome.i18n.getMessage(f?f:"b1");t.style.display=c?"inline-block":"none";m.style.display="block";c&&(t.addEventListener("click",
n,!1),t.focus());b&&(q.addEventListener("click",l,!1),q.focus());r();window.addEventListener("resize",r,!1)}function n(a){var b=this.id,c="about:blank";"support"==b||"help"==b||"logo"==b||"fox"==b?Y(function(a){a?("support"==b?c="http://www.hotcleaner.com/security-and-privacy-software-feedback.html#chvijda":"fox"==b?c="http://www.hotcleaner.com/clickclean_firefox.html":"help"==b?c="http://www.hotcleaner.com/clickclean-quick-start-guide.html":"logo"==b&&(c="http://www.hotcleaner.com/"),C(c,!0)):("support"==
b?c="https://www.facebook.com/clickclean":"fox"==b?c="https://addons.mozilla.org/en-us/firefox/addon/clickclean/":"help"==b?c="https://www.facebook.com/clickclean":"ssl"==b?c="https://support.google.com/websearch/answer/173733":"logo"==b&&(c="https://chrome.google.com/webstore/detail/ghgabhipcejejjmhhchfonmamedcbeod"),C(c,!1))}):("ctrb"==b?c=chrome.runtime.getURL("ctrb.html"):"ghist"==b?c="https://history.google.com/history/settings?st=tr":"appearance"==b?c="http://www.hotcleaner.com/clickclean-appearance.html":
"sync"==b&&(c="https://www.google.com/settings/chrome/sync"),C(c,!1))}function P(){function a(a,b,c,f,h){a=g(a);b&&("web"==a.className?a.firstElementChild.textContent=b:a.textContent=b);c&&(a.title=c);-1<h&&(a.sid=h,a.style.backgroundImage="url(i/s"+h+".png)");f&&a.addEventListener("click",f,!1)}var b=chrome.i18n.getMessage("cleaner1").split(";");chrome.i18n.getMessage("share").split(";");var c=new Uint8Array(1);crypto.getRandomValues(c);c=c[0]%7;a("logo","v"+f.ver,0,n);a("fox","Get for Firefox!",
0,n);a("ctrb",b[0],b[2],n);a("clear",b[3],0,V);a("hist",b[4],b[5],function(){m("http://www.hotcleaner.com/clear-browsing-history.html",chrome.runtime.getURL("history.html"))});a("support",b[6],0,n);a("help",b[7],0,n);a("reset0",b[8],b[13],D);a("reset1",b[9],b[13],D);a("reset2",b[10],b[13],D);a("dev",b[11],b[12],function(){f.dev?(f.dev=0,q(),u()):p("m4",function(){f.dev=1;q();u()},r)});a("export",b[14],0,Z);a("import",b[15],0,aa);a("ghist",b[16],b[16],n);a("sync",b[17],b[17],n);a("appearance",b[18],
b[18],n)}function u(){for(var a=g("dev"),b=document.getElementsByClassName("dev"),c=f.dev?"":"none",d=0;d<b.length;++d)b[d].style.display=c;f.dev?a.setAttribute("on",!0):a.removeAttribute("on")}function D(a){a=parseInt(this.id.slice(5));2!=a||f.p5?M(a):p("m5a",function(){M(2)},r)}function M(a){var b;0==a?b=[10,0,1,1,1,0,0,0,0,0,0,0,0,0,0]:1==a?b=[10,0,1,1,1,0,0,1,0,1,1,1,1,1,1]:2==a&&(b=[10,0,1,1,1,1,1,1,1,1,1,1,1,1,1]);f.timeType=b[0];f.time=b[1];f.p1=b[2];f.p2=b[3];f.p3=b[4];f.p4=b[5];f.p5=b[6];
f.p6=b[7];f.p7=b[8];f.p8=b[9];f.p9=b[10];f.p10=b[11];f.p11=b[12];f.p12=b[13];g("timeType").selectedIndex=f.timeType;y();for(b=0;14>b;b++)a=g("p"+b),f[a.id]?a.setAttribute("on",!0):a.removeAttribute("on");f.p31=1;f.p32=1;g("p31").setAttribute("on",!0);g("p32").setAttribute("on",!0)}function H(a){window.Audio&&(new Audio("erased.ogg")).play();a&&setTimeout(a,400)}function O(a){for(var b=[chrome.runtime.getURL(""),"http://www.hotcleaner.com/","https://www.hotcleaner.com/","https://hotcleaner.com/","http://hotcleaner.com/"],
c=0,d=b.length;c<d;c++)if(0==a.indexOf(b[c]))return;document.location.href="about:blank"}function m(a,b){h(1,0);l("m8",1500);chrome.runtime.sendMessage('{"id":8,"v":"'+a+'","v3":"'+b+'"}');h(0,0)}function C(a,b){chrome.runtime.sendMessage('{"id":9,"v":"'+a+'","i":'+(b?1:0)+"}")}function Z(){chrome.runtime.sendMessage('{"id":34}',function(a){var b;a=JSON.stringify({opt:f,wl:a});Blob?b=new Blob([a],{type:"application/json;charset=UTF-8"}):BlobBuilder&&(b=new BlobBuilder,b.append(a),b=b.getBlob("application/json;charset=UTF-8"));
ba(b,"ClickClean-v"+f.ver+"-Options.json")})}function aa(){ca(1E5,function(a){try{a=JSON.parse(a)}catch(h){l("m12",1E3);return}var b=a.opt,c=f.ver,d=f.nv;a.wl&&chrome.runtime.sendMessage(JSON.stringify({id:35,v:a.wl}));for(var e in b)void 0!=f[e]&&(f[e]=b[e]);f.ver=c;f.nv=d;g("timeType").selectedIndex=f.timeType;y();for(a=0;33>a;a++)el=g("p"+a),f[el.id]?el.setAttribute("on",!0):el.removeAttribute("on");u();l("m8",1E3)})}function ca(a,b){var c=g("openAs");c&&document.body.removeChild(c);c=document.createElement("input");
c.id="openAs";c.style.display="none";c.type="file";document.body.appendChild(c);c.addEventListener("change",function(c){if((c=c.target.files)&&1==c.length&&c[0].size<a){var e=new FileReader;e.onload=function(a){b(a.target.result)};e.readAsText(c[0])}else l("m12",1E3)},!1);c.click()}function ba(a,b){h(1,0);var c=document.createElement("a"),d=window.webkitURL||window.URL;c.href=d.createObjectURL(a);c.setAttribute("download",b);c.click();setTimeout(function(){d.revokeObjectURL(c.href);h(0,0)},2E3)}function Y(a){var b=
new Image;b.onload=function(){a(1)};b.onerror=function(){a()};b.onabort=function(){a()};b.src="http://www.hotcleaner.com/img/1.gif?t="+(new Date).getTime()}function W(a,b){try{v=JSON.parse(localStorage[a])}catch(c){v=null}return null===v||v.constructor!==b?null:v}function g(a){return document.getElementById(a)}function r(){}var z,f,x;window.addEventListener("DOMContentLoaded",function(){chrome.runtime.sendMessage('{"id":1}',N)},!1)})();
