// Click&Clean for Google Chrome - HOTCLEANER.COM - Copyright (c) 2016 Vlad & Serge Strukoff. All Rights Reserved.
(function(){function B(a){a:{for(var b=[chrome.runtime.getURL(""),"http://www.hotcleaner.com/","https://www.hotcleaner.com/","https://hotcleaner.com/","http://hotcleaner.com/"],c=0,e=b.length;c<e;c++)if(0==a.indexOf(b[c]))break a;document.location.href="about:blank"}a=chrome.i18n.getMessage("cookies").split(";");b=document.body.innerHTML;for(c=0;e=a[c];c++)b=b.replace(new RegExp("t"+(10+c),"gm"),e);document.body.innerHTML=b;h("sel0").addEventListener("click",v,!1);h("sel1").addEventListener("click",
v,!1);h("ref").addEventListener("click",w,!1);h("del0").addEventListener("click",C,!1);h("toc0").addEventListener("click",D,!1);h("toc1").addEventListener("click",E,!1);w();a=h("services");for(var b=[{n:"Google | G+, GMail, YouTube, ...",d0:"accounts.google.com",d1:"google.com",i:1},{n:"Facebook",d0:"facebook.com",i:2},{n:"Twitter",d0:"twitter.com",i:3},{n:"Yahoo",d0:"yahoo.com",i:4},{n:"Microsoft | SkyDrive, Live Mail, ...",d0:"login.live.com",d1:"live.com",i:5}],e=document.createDocumentFragment(),
f=0,d;d=b[f];f++)c=document.createElement("button"),c.className="btn",c.style.cssFloat="left",c.title=d.n,c.setAttribute("data-d0",d.d0),d.d1&&c.setAttribute("data-d1",d.d1),c.style.backgroundImage="url(i/fav/"+d.i+".png)",c.addEventListener("click",F,!1),e.appendChild(c);a.appendChild(e)}function w(){n(1);h("list0").innerHTML=h("list1").innerHTML="";chrome.runtime.sendMessage('{"id":30}',function(a){var b=a[0];a=a[1];var c=[],e,f,d=0,g=0,m=0;if(0<b.length){for(var l=0,k;k=b[l];l++)"."==k.charAt(0)&&
(b[l]=k.slice(1));b.sort(function(a,b){return a<b?-1:1});e=a.indexOf(b[0]);for(l=0;k=b[l];l++)f!=k&&(0<d&&(0>e?(c.push(d),g+=d):(a[e+1]=d,m+=d),d=0),e=a.indexOf(k),0>e&&c.push(k)),d++,f=k;0<d&&(0>e?(c.push(d),g+=d):(a[e+1]=d,m+=d))}x(0,c,1,1);x(1,a,0,0);h("cnt0").textContent=" ("+g+")";h("cnt1").textContent=" ("+m+")";n(0)})}function v(a){a=u(this,"on");for(var b=this.parentElement.nextElementSibling.children,c=0,e;e=b[c];c++)p(e.firstElementChild,"on",a),p(e,"on",a)}function G(a){var b=this.parentNode.getAttribute("data-domain");
chrome.runtime.sendMessage('{"id":9,"v":"http://'+b+'"}');a.stopPropagation()}function H(a){a.stopPropagation();a=this.parentNode;var b=a.parentNode.getAttribute("data-id"),c=a.getAttribute("data-domain"),e=parseInt(a.getAttribute("data-count"));chrome.runtime.sendMessage(JSON.stringify({id:32,v:[c]}));a.parentElement.removeChild(a);q(b,-e);1==b&&r()}function C(a){n(1);var b=this.parentElement.nextElementSibling;a=b.querySelectorAll(".item[on]");if(0<a.length){for(var c=[],b=b.getAttribute("data-id"),
e,f=0,d=0,g;g=a[d];d++)e=g.getAttribute("data-domain"),c.push(e),f+=parseInt(g.getAttribute("data-count")),g.parentElement.removeChild(g);chrome.runtime.sendMessage(JSON.stringify({id:32,v:c}));q(b,-f)}n(0)}function D(){n(1);y(1,0);r()}function E(a){n(1);y(0,1);r()}function r(){for(var a=[],b=h("list1").children,c=0,e;e=b[c];c++)a.push(e.getAttribute("data-domain"),0);chrome.runtime.sendMessage(JSON.stringify({id:35,v:a}));n(0)}function y(a,b){var c=h("list"+a).querySelectorAll(".item[on]");if(0<
c.length){for(var e=[],f=0,d;d=c[f];f++)e.push(d.parentNode.removeChild(d));z(a,b,e)}}function q(a,b){var c=h("cnt"+a),e=parseInt(c.textContent.slice(2));c.textContent=" ("+(e+b)+")"}function u(a,b){var c=a.hasAttribute(b);c?a.removeAttribute(b):a.setAttribute(b,!0);return!c}function p(a,b,c){c?a.setAttribute(b,!0):a.removeAttribute(b)}function I(a){var b=this.hasAttribute("on");if(a.shiftKey){if(0>t&&(t=this.parentNode.firstElementChild),a=!b,b=t,this&&b){var c=this;c.getAttribute("data-domain")>
b.getAttribute("data-domain")&&(c=b,b=this);for(;c&&c.getAttribute("data-domain")<=b.getAttribute("data-domain");)p(c,"on",a),p(c.firstElementChild,"on",a),c=c.nextElementSibling}}else u(this.firstElementChild,"on"),u(this,"on");t=this}function A(a,b,c,e){var f,d,g,h,l,k;f=document.createElement("div");d=document.createElement("button");g=document.createElement("div");h=document.createElement("label");l=document.createElement("button");k=document.createElement("button");f.className="item";d.className=
"chk";h.className="label elps";k.className="btn link";l.className="btn del";f.setAttribute("data-domain",a);f.setAttribute("data-count",b);e&&(d.setAttribute("on",!0),f.setAttribute("on",!0));h.textContent=a+(c?" ("+b+")":"");d.appendChild(g);f.appendChild(d);f.appendChild(h);f.appendChild(l);f.appendChild(k);l.addEventListener("click",H,!1);k.addEventListener("click",G,!1);f.addEventListener("click",I,!1);return f}function x(a,b,c,e){a=h("list"+a);for(var f,d=document.createDocumentFragment(),g=
0;f=b[g];g+=2)f=A(f,b[g+1],c,e),d.appendChild(f);a.appendChild(d)}function z(a,b,c){for(var e=h("list"+b),f,d,g,m=0,l=g=0,k;k=c[l];l++){g=!0;f=k.getAttribute("data-domain");for(var n=0,p;p=e.children[n];n++)if(d=p.getAttribute("data-domain"),f==d){g=!1;break}else if(f<d){g=parseInt(k.getAttribute("data-count"));m+=g;d=k.firstElementChild.nextElementSibling;d.textContent=0==b?f+" ("+g+")":f;e.insertBefore(k,p);g=!1;break}g&&(g=parseInt(k.getAttribute("data-count")),m+=g,d=k.firstElementChild.nextElementSibling,
d.textContent=0==b?f+" ("+g+")":f,e.appendChild(k))}0<m&&(q(a,-m),q(b,m))}function F(a){for(var b,c=0;2>c;c++)if(a=this.getAttribute("data-d"+c)){a:{b=a;for(var e=h("list0").children,f=void 0,d=0,g=void 0;g=e[d];d++)if(f=g.getAttribute("data-domain"),f==b){b=g;break a}b=0}b=b?b.parentNode.removeChild(b):A(a,0,0,1);z(0,1,[b])}r()}function n(a){h("shade").style.display=a?"block":"none"}function h(a){return document.getElementById(a)}var t=-1;window.addEventListener("DOMContentLoaded",function(){chrome.runtime.sendMessage('{"id":2}',
B)},!1)})();
